# Generated by Django 3.2.4 on 2022-11-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=200)),
                ('numCuenta', models.PositiveIntegerField()),
                ('saldo', models.PositiveIntegerField()),
            ],
        ),
    ]
